- hosts: all
  become: yes
  vars:
    user: vagrant
    galaxy_repo: https://github.com/common-workflow-language/galaxy.git
  tasks:
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Add docker key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add docker repo
      apt_repository: repo='deb [arch=amd64] http://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable' state=present

    - name: Install packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - zsh
        - screen
        - tmux
        - python-pip
        - docker-ce
        - tree
        - openjdk-8-jre

    - name: Add docker group
      user: name={{user}} append=yes groups=docker

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Start services
      action: service name={{item}} state=started enabled=yes
      with_items:
        - docker

    - name: Clone galaxy repository
      git:
        repo: https://github.com/common-workflow-language/galaxy.git
        depth: 1
        dest: /home/{{user}}/galaxy
      become_user: "{{user}}"

    - name: "Galaxy host 0.0.0.0"
      lineinfile: >-
        dest=/home/{{user}}/galaxy/config/galaxy.ini.sample
        state=present
        backrefs=yes
        regexp='^#host'
        line='host = 0.0.0.0'
      become_user: "{{user}}"

    - name: Run Galaxy run.sh --daemon
      command: sh /home/{{user}}/galaxy/run.sh --daemon
      become_user: "{{user}}"
