- hosts: all
  become: yes
  vars:
    user: vagrant
    galaxy_repo: https://github.com/common-workflow-language/galaxy.git
  tasks:
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Add docker key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add docker repo
      apt_repository: repo='deb [arch=amd64] http://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable' state=present

    - name: Install packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - zsh
        - screen
        - tmux
        - python-pip
        - docker-ce
        - tree
        - openjdk-8-jre

    - name: Add docker group
      user: name={{user}} append=yes groups=docker

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Start services
      action: service name={{item}} state=started enabled=yes
      with_items:
        - docker

    - name: Clone galaxy repository
      git:
        repo: https://github.com/common-workflow-language/galaxy.git
        depth: 1
        dest: /home/{{user}}/galaxy
      become_user: "{{user}}"

    - name: "Galaxy host 0.0.0.0"
      lineinfile: >-
        dest=/home/{{user}}/galaxy/config/galaxy.ini.sample
        state=present
        backrefs=yes
        regexp='^# available network interfaces.'
        insertafter=yes
        line='host = 0.0.0.0'
      become_user: "{{user}}"
    - name: "Add admin user"
      lineinfile: >-
        dest=/home/{{user}}/galaxy/config/galaxy.ini.sample
        state=present
        backrefs=yes
        regexp='^#admin_users = None'
        line='admin_users = admin@galaxy.org'
      become_user: "{{user}}"
    - name: Run Galaxy run.sh --daemon
      command: sh /home/{{user}}/galaxy/run.sh --daemon
      become_user: "{{user}}"
    - name: wait for Galaxy port up
      wait_for:
        port=8080
        state=started
        delay=30
        timeout=500
      #delegate_to: 127.0.0.1
    - name: Get create_galaxy_user.py
      get_url:
        url: https://raw.githubusercontent.com/galaxyproject/ansible-galaxy-extras/master/templates/create_galaxy_user.py.j2
        dest: /home/{{user}}/create_galaxy_user.py
    - name: "Replace create_galaxy_user.py"
      replace: >-
        dest=/home/{{user}}/create_galaxy_user.py
        regexp={{ item.src }}
        replace={{ item.dst }}
      become_user: "{{user}}"
      with_items:
        - { src: '\{\{ use_pbkdf2 \}\}', dst: 'False' } # replace use_pbkdf2
        - { src: '\{\{ galaxy_server_dir \}\}', dst: '/home/{{user}}/galaxy' } # replace library path
    - name: Create admin user by create_galaxy_user.py
      shell: source .venv/bin/activate ; python /home/{{user}}/create_galaxy_user.py --user admin@galaxy.org --password admin --key admin
      args:
        chdir: /home/{{user}}/galaxy
      become_user: "{{user}}"
